USE StudentCLUB_Database;
CREATE TABLE Member (
SSN VARCHAR(20) PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Age INT CHECK (Age > 0),
StreetAddress VARCHAR(255)
);
CREATE TABLE Student (
SSN VARCHAR(20) PRIMARY KEY,
CourseName VARCHAR(100),
GPA DECIMAL (3,2) NOT NULL CHECK (GPA >= 0 AND GPA <= 4.0),
FOREIGN KEY (SSN) REFERENCES Member (SSN) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE Alumni(
SSN VARCHAR(20) PRIMARY KEY,
GraduationYear INT CHECK (GraduationYear >= 1900 AND GraduationYear <= 2025),
DegreeTitle VARCHAR(100) NOT NULL,
MajorField VARCHAR(100),
FOREIGN KEY (SSN) REFERENCES Member (SSN) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE Clubs(
ClubID INT PRIMARY KEY,
ClubName VARCHAR(100) NOT NULL,
LeaderSSN VARCHAR(20),
FOREIGN KEY (LeaderSSN) REFERENCES Member (SSN) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE `Groups` (
GroupID INT PRIMARY KEY,
GroupName VARCHAR(100) NOT NULL
);
CREATE TABLE ClubGroups (
ClubID INT,
GroupID INT ,
PRIMARY KEY (ClubID,GroupID),
FOREIGN KEY (ClubID) REFERENCES Clubs(ClubID) ON DELETE CASCADE,
FOREIGN KEY (GroupID) REFERENCES `Groups`(GroupID) ON DELETE CASCADE
);
CREATE TABLE Location(
 LocID INT PRIMARY KEY,
 RoomNumber VARCHAR(20) NOT NULL,
 FloorNumber INT,
 BuildingName VARCHAR(100) NOT NULL
);
CREATE TABLE Events(
EventID INT PRIMARY KEY,
EventDate DATE NOT NULL,
EventTime TIME,
Subject VARCHAR(255) NOT NULL,
RegistrationFee DECIMAL(10,2) DEFAULT 0.00 CHECK (RegistrationFee >= 0),
LocID INT,
FOREIGN KEY (LocID) REFERENCES Location(LocID) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE ClubsGroupsEvents(
ClubID INT,
GroupID INT,
EventID INT,
PRIMARY KEY (ClubID,GroupID,EventID),
FOREIGN KEY (ClubID,GroupID) REFERENCES ClubGroups(ClubID,GroupID),
FOREIGN KEY (EventID) REFERENCES Events(EventID) ON DELETE CASCADE
);
CREATE TABLE FundedProjects(
ProjectID INT PRIMARY KEY,
TotalBudget DECIMAL(12,2) NOT NULL CHECK (TotalBudget >= 0),
BudgetPortion DECIMAL(5,2) CHECK (BudgetPortion >= 0 AND BudgetPortion <= 100),
ProjectFunction VARCHAR(255) NOT NULL
);
CREATE TABLE  ClubsGroupsFundedProjects(
ClubID INT,
GroupID INT,
ProjectID INT,
PRIMARY KEY (ClubID,GroupID,ProjectID),
FOREIGN KEY (ClubID,GroupID) REFERENCES ClubGroups(ClubID,GroupID)ON DELETE CASCADE,
FOREIGN KEY (ProjectID) REFERENCES FundedProjects(ProjectID)ON DELETE CASCADE
);
CREATE TABLE AlumniWorkHistory(
SSN VARCHAR(20),
CompanyName VARCHAR(100) NOT NULL,
StartDate DATE NOT NULL,
JobTitle VARCHAR(100),
PRIMARY KEY (SSN,CompanyName,StartDate),
FOREIGN KEY (SSN) REFERENCES Alumni(SSN) ON DELETE CASCADE
);
CREATE TABLE MemberGroupMembership(
SSN VARCHAR(20),
ClubID INT,
GroupID INT,
MembershipStart DATE NOT NULL,
MembershipEnd DATE,
PRIMARY KEY (SSN,ClubID,GroupID),
FOREIGN KEY (SSN) REFERENCES Member(SSN)ON DELETE CASCADE,
FOREIGN KEY (ClubID,GroupID) REFERENCES ClubGroups(ClubID,GroupID)ON DELETE CASCADE
);
CREATE TABLE MemberProjectPayments(
SSN VARCHAR(20),
ClubID INT,
GroupID INT,
ProjectID INT,
PaymentAmount DECIMAL(10,2) NOT NULL CHECK (PaymentAmount >= 0),
PRIMARY KEY (SSN,ClubID,GroupID,ProjectID),
FOREIGN KEY (SSN) REFERENCES Member(SSN) ON DELETE CASCADE,
FOREIGN KEY (ClubID,GroupID) REFERENCES ClubGroups(ClubID,GroupID) ON DELETE CASCADE,
FOREIGN KEY (ProjectID) REFERENCES FundedProjects(ProjectID) ON DELETE CASCADE
);
CREATE TABLE MemberGroupLeaders(
SSN VARCHAR(20),
ClubID INT,
GroupID INT,
PRIMARY KEY (SSN,ClubID,GroupID),
FOREIGN KEY (SSN) REFERENCES Member(SSN)ON DELETE CASCADE,
FOREIGN KEY (ClubID,GroupID) REFERENCES ClubGroups(ClubID,GroupID)ON DELETE CASCADE
);

